import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Button from '@/Components/Button'
import Footer from '@/Components/Footer'
import BoldButton from '@/Components/BoldButton'

export default function Home() {
  return (
    <>
      <Head>
        <title>X, It's what's happening/ X</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/twitterFavicon.ico" />
      </Head>
      <header>

      </header>
      <main>
        <div className={styles.main}>
            <div className={styles.logoContainer}>
              <img src={'/images/twitterLogo.svg'}></img>
            </div>
          <div className={styles.sub}>
            <div className={styles.one}>Happening now</div>
              <div className={styles.subSub}>
              <span className={styles.two}>Join today.</span>
                <div className={styles.subSubSub}>
                    <Button title="Sign up with Google" border="none"/>
                      <div className={styles.weight}>
                        <BoldButton title="Sign up with Apple" border="none"/> 
                      </div>
                    <div className={styles.mainLine}>
                      <div className={styles.line}></div> 
                       or
                      <div className={styles.line}></div>
                    </div>
                <BoldButton title="Create Account" backgroundColor="rgb(29,161,242)" color="rgb(255,255,255)" border="none"/>
                <div className={styles.Text}>
                  <span className={styles.whiteText}>By signing up, you agree to the<span className={styles.blueText}> Terms of Service </span>and <span className={styles.blueText}>Privacy Policy</span>, including <span className={styles.blueText}>Cookie Use.</span></span>
                </div>
                <span className={styles.three}>Already have an account?</span>
                  <div className={styles.signUp}>
                    <BoldButton title="Sign in" backgroundColor="rgb(00,00,00)" color="rgb(29,161,242)" border="solid grey 0.2px"/>
                  </div>
                </div>
              </div>
          </div>
        </div>
        <Footer/>
      </main>
    </>
  )
}
